[package]
name = "commando"
version = "0.1.0"
authors = ["Bailey Cosier <bailey@crowdist.com>"]

[dependencies]
libc = "0.2.22"

cursive = { git = "https://github.com/gyscos/Cursive" }
jfs = { path = "./lib/rust-json-file-store" }

serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"



